{% set name = "ee-client" %}
{% set version = "2.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace('-', '_') }}-{{ version }}.tar.gz
  sha256: f8c42442d4da183f559ed4fe8e8813f1ab588aaca8992c5f1d730c2b734b8ce5

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=61.2
  run:
    - python >={{ python_min }}
    - earthengine-api
    - httpx
    - h2
    - tenacity
    - pydantic

test:
  imports:
    - eeclient
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/dfguerrerom/ee-client
  summary: Multi-user session client for Google Earth Engine with custom authentication
  description: |
    ee-client extends the Earth Engine API with custom session management and
    client interactions for multi-user environments.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/dfguerrerom/ee-client

extra:
  recipe-maintainers:
    - dfguerrerom
